### PR TITLE
Updates zenodo badge

### PR DESCRIPTION
**Pull request by lcortesg**

### CODE REVIEW

**Comment by aweinstein** [comment]
We don't appear as the authors:

image

It should appear our team.

**Comment by lcortesg** [comment]
Fixed with the same tag number

**Review by aweinstein — APPROVED** [review]

**Comment by aweinstein** [comment]
@lcortesg The PyPi check is failing:

image

**Comment by lcortesg** [comment]
It's failing because I re-used the tag on GitHub, I didn't wanted to release a new version pypi without any changes to the code.

The re-used tag successfully updated on zenodo, but will not update the pypi version until a new tag is released.

**Comment by aweinstein** [comment]
> It's failing because I re-used the tag on GitHub, I didn't wanted to release a new version pypi without any changes to the code.
> 
> The re-used tag successfully updated on zenodo, but will not update the pypi version until a new tag is released.

Just push the version by one this time.

**Comment by lcortesg** [comment]
Build is passing now, and the Zenodo badge automatically points no the newest release, with updates authors and affiliations.

**Comment by lcortesg** [comment]
Funding and grant info added

**Review by aweinstein — APPROVED** [review]

**Pull request merged**
